import type { TableColumnDefinition } from '@/shared/hooks/use-table-column-visibility'

export const CLIENT_TRAVELERS_TABLE_COLUMN_WIDTHS = {
  selection: '2.75rem',
  reference: '4.25rem',
  name: '22%',
  role: '10%',
  status: '6.5rem',
  passengerType: '5.5rem',
  nationality: '6.5rem',
  vipLevel: '5.5rem',
  gender: '5.5rem',
  age: '3.5rem',
  passportStatus: '7rem',
  passportExpiry: '6.5rem',
  visaStatus: '6.5rem',
  email: '16%',
  phone: '9rem',
  whatsapp: '9rem',
  country: '7rem',
  city: '7rem',
  occupation: '9rem',
  company: '9rem',
  preferredLanguage: '6rem',
  category: '8rem',
  riskLevel: '5.5rem',
  updated: '6.5rem',
  created: '6.5rem',
  notes: '14%',
  actions: '3.25rem',
} as const

export type ClientTravelersTableColumnKey = keyof typeof CLIENT_TRAVELERS_TABLE_COLUMN_WIDTHS

export const CLIENT_TRAVELERS_TABLE_DEFAULT_COLUMN_ORDER: ClientTravelersTableColumnKey[] = [
  'selection',
  'reference',
  'name',
  'role',
  'status',
  'passengerType',
  'nationality',
  'vipLevel',
  'gender',
  'age',
  'passportStatus',
  'passportExpiry',
  'visaStatus',
  'email',
  'phone',
  'whatsapp',
  'country',
  'city',
  'occupation',
  'company',
  'preferredLanguage',
  'category',
  'riskLevel',
  'updated',
  'created',
  'notes',
  'actions',
]

export const CLIENT_TRAVELERS_TABLE_DEFAULT_VISIBLE_KEYS: ClientTravelersTableColumnKey[] = [
  'selection',
  'reference',
  'name',
  'role',
  'status',
  'actions',
]

export const CLIENT_TRAVELERS_TABLE_COLUMN_OPTIONS: TableColumnDefinition<ClientTravelersTableColumnKey>[] =
  [
    { key: 'selection', label: 'Select', locked: true },
    { key: 'reference', label: 'ID', locked: true },
    { key: 'name', label: 'Name', locked: true },
    { key: 'role', label: 'Role', defaultVisible: true },
    { key: 'status', label: 'Status', defaultVisible: true },
    { key: 'passengerType', label: 'Passenger type', defaultVisible: false },
    { key: 'nationality', label: 'Nationality', defaultVisible: false },
    { key: 'vipLevel', label: 'VIP level', defaultVisible: false },
    { key: 'gender', label: 'Gender', defaultVisible: false },
    { key: 'age', label: 'Age', defaultVisible: false },
    { key: 'passportStatus', label: 'Passport status', defaultVisible: false },
    { key: 'passportExpiry', label: 'Passport expiry', defaultVisible: false },
    { key: 'visaStatus', label: 'Visa status', defaultVisible: false },
    { key: 'email', label: 'Email', defaultVisible: false },
    { key: 'phone', label: 'Phone', defaultVisible: false },
    { key: 'whatsapp', label: 'WhatsApp', defaultVisible: false },
    { key: 'country', label: 'Country', defaultVisible: false },
    { key: 'city', label: 'City', defaultVisible: false },
    { key: 'occupation', label: 'Occupation', defaultVisible: false },
    { key: 'company', label: 'Company', defaultVisible: false },
    { key: 'preferredLanguage', label: 'Language', defaultVisible: false },
    { key: 'category', label: 'Category', defaultVisible: false },
    { key: 'riskLevel', label: 'Risk level', defaultVisible: false },
    { key: 'updated', label: 'Updated', defaultVisible: false },
    { key: 'created', label: 'Created', defaultVisible: false },
    { key: 'notes', label: 'Notes', defaultVisible: false },
    { key: 'actions', label: 'Actions', locked: true },
  ]
