import type { ClientFormInput } from './use-client-mutations'

export const EMPTY_CLIENT_FORM: ClientFormInput = {
  displayName: '',
  firstName: '',
  middleName: '',
  lastName: '',
  type: 'individual',
  status: 'active',
  email: '',
  phone: '',
  company: '',
  industry: undefined,
  jobTitle: '',
  country: '',
  city: '',
  address: '',
  preferredCurrency: 'EGP',
  paymentCurrencies: [],
  preferredLanguage: 'en',
  preferredPaymentMethods: [],
  paymentTermId: undefined,
  billingAccount: 'prepaid',
  creditLimit: undefined,
  sla: undefined,
  slaAgreement: undefined,
  market: undefined,
  segment: '',
  customerTier: undefined,
  acquisitionSource: undefined,
  acquisitionChannel: undefined,
  dateOfBirth: undefined,
  gender: undefined,
  accountManagerId: undefined,
  membership: 'non_member',
  membershipNotes: '',
  preferredDestination: '',
  nationalityFocus: '',
  billingNotes: '',
  commercialRegistration: undefined,
  taxRegistration: undefined,
  notes: '',
  joinedAt: undefined,
}
